<#
.SYNOPSIS
    READ-ONLY snapshot inventory and comparison across every configured ONTAP cluster.

.DESCRIPTION
    Queries `vol snapshot show` on each cluster selected from config.json, normalises the
    output, and writes deterministic CSV reports that let you compare snapshots across
    clusters — all records, the oldest, the largest, and the records that cross the
    configurable age / size thresholds.

    Collection uses the per-cluster SSH helper generated by Load-Config.ps1
    (`<cluster>-ssh`), matching the workspace convention of driving ONTAP through its CLI
    so the output stays raw and auditable.

    THIS SCRIPT NEVER DELETES A SNAPSHOT. The only ONTAP command it issues is
    `vol snapshot show`, built and validated by Get-SnapshotInventoryCommand.

.PARAMETER Cluster
    Restrict to one cluster by Alias or cluster name (passed to Get-OntapTargetClusters).
    Omit for every cluster in config.json.

.PARAMETER VIP
    Restrict to VIP-marked clusters.

.PARAMETER AgeDays
    A snapshot at or above this age (days) is an old candidate. Default 90.

.PARAMETER LargeThresholdGB
    A snapshot at or above this size (GiB) is a large candidate. Default 100.

.PARAMETER TopLargest
    How many rows in the largest-N report. Default 50.

.PARAMETER TopOldest
    How many rows in the oldest-N report. Default 50.

.PARAMETER Svm
    Optional ONTAP-side -vserver filter.

.PARAMETER Volume
    Optional ONTAP-side -volume filter.

.PARAMETER OutputPath
    Directory for the reports. Default scripts\snapshots\reports\<timestamp>.

.PARAMETER SaveRaw
    Also write each cluster's untouched SSH output to raw\<cluster>.txt, so a run can be
    re-analysed later with -ReplayFrom without touching a cluster.

.PARAMETER ReplayFrom
    Directory of previously captured raw\<cluster>.txt files. Reports are rebuilt from
    those files and NO cluster is contacted. Useful for offline analysis and for
    reproducing a report.

.PARAMETER ConfigRoot
    Folder holding config.json. Defaults to the repository root. Set this when running
    from a git worktree that has no local config.json of its own.

.EXAMPLE
    .\scripts\snapshots\Get-SnapshotComparison.ps1
    All clusters, default thresholds (90 days / 100 GiB), reports under scripts\snapshots\reports.

.EXAMPLE
    .\scripts\snapshots\Get-SnapshotComparison.ps1 -Cluster example-cluster -AgeDays 30 -LargeThresholdGB 50 -TopLargest 100

.EXAMPLE
    .\scripts\snapshots\Get-SnapshotComparison.ps1 -VIP -SaveRaw
    .\scripts\snapshots\Get-SnapshotComparison.ps1 -ReplayFrom .\scripts\snapshots\reports\20260730_181500 -AgeDays 365
    Capture once, then re-threshold offline as often as you like.
#>
[CmdletBinding()]
param(
    [string]$Cluster,
    [switch]$VIP,
    [double]$AgeDays = 90,
    [double]$LargeThresholdGB = 100,
    [int]$TopLargest = 50,
    [int]$TopOldest = 50,
    [string]$Svm,
    [string]$Volume,
    [string]$OutputPath,
    [switch]$SaveRaw,
    [string]$ReplayFrom,
    [string]$ConfigRoot
)

$ErrorActionPreference = 'Stop'

$repoRoot  = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$modulePath = Join-Path $PSScriptRoot 'Get-SnapshotInventory.psm1'
Import-Module $modulePath -Force

if ($AgeDays -lt 0)          { throw "-AgeDays must not be negative." }
if ($LargeThresholdGB -lt 0) { throw "-LargeThresholdGB must not be negative." }
$largeBytes = [int64][math]::Round($LargeThresholdGB * 1GB)

$runStamp = Get-Date -Format 'yyyyMMdd_HHmmss'
if (-not $OutputPath) {
    $OutputPath = Join-Path $PSScriptRoot "reports\$runStamp"
}
$null = New-Item -ItemType Directory -Path $OutputPath -Force

$now      = Get-Date
$records  = [System.Collections.Generic.List[object]]::new()
$problems = [System.Collections.Generic.List[object]]::new()
$sources  = [System.Collections.Generic.List[object]]::new()

function Add-Problem {
    param([string]$Cluster, [string]$Stage, [string]$Detail)
    $problems.Add([PSCustomObject]@{ Cluster = $Cluster; Stage = $Stage; Detail = $Detail })
    Write-Host "  ! $Cluster — $Stage : $Detail" -ForegroundColor Yellow
}

# --- Gather raw output, either from clusters or from a previous capture ------------
if ($ReplayFrom) {
    $rawDir = if (Test-Path -LiteralPath (Join-Path $ReplayFrom 'raw')) {
        (Resolve-Path (Join-Path $ReplayFrom 'raw')).Path
    } else {
        (Resolve-Path $ReplayFrom).Path
    }
    Write-Host "REPLAY mode — no cluster will be contacted. Source: $rawDir" -ForegroundColor Magenta

    $files = @(Get-ChildItem -LiteralPath $rawDir -Filter '*.txt' -File | Sort-Object Name)
    if ($files.Count -eq 0) { throw "No raw capture files (*.txt) found under $rawDir" }

    foreach ($f in $files) {
        $alias = [IO.Path]::GetFileNameWithoutExtension($f.Name)
        $lines = @(Get-Content -LiteralPath $f.FullName)
        $sources.Add([PSCustomObject]@{ Cluster = $alias; Source = $f.FullName; Lines = $lines })
    }
}
else {
    # Config-driven cluster enumeration — never a hardcoded cluster list.
    #
    # Load-Config.ps1 must be dot-sourced inside a function, NOT at script scope. Its
    # per-cluster generator loop assigns $cluster in the caller's scope, and PowerShell
    # variable names are case-insensitive, so dot-sourcing it at script scope silently
    # overwrites this script's own -Cluster parameter with the LAST cluster in config.json.
    # Symptom: `-Cluster <alias>` quietly reports on a completely different cluster.
    # Everything Load-Config.ps1 publishes ($global:ONTAP_Clusters, Get-OntapTargetClusters,
    # Invoke-OntapCsv, the per-cluster <cluster>-ssh functions and aliases) is declared
    # global, so confining the dot-source to a function loses nothing.
    function Import-OntapWorkspaceConfig {
        param([Parameter(Mandatory)][string]$Root)
        $rootDir = $Root
        . (Join-Path $Root 'Load-Config.ps1')
    }

    $configRootPath = if ($ConfigRoot) { (Resolve-Path $ConfigRoot).Path } else { $repoRoot }
    Import-OntapWorkspaceConfig -Root $configRootPath

    $targetArgs = @{}
    if ($Cluster) { $targetArgs['Cluster'] = $Cluster }
    if ($VIP)     { $targetArgs['VIP']     = $true }
    $targets = @(Get-OntapTargetClusters @targetArgs)
    if ($targets.Count -eq 0) { throw "No clusters selected from $configRootPath\config.json" }

    $cmd = Get-SnapshotInventoryCommand -Svm $Svm -Volume $Volume
    Write-Host "ONTAP command: $cmd" -ForegroundColor DarkGray
    Write-Host "Clusters: $(($targets | ForEach-Object { $_.Alias }) -join ', ')" -ForegroundColor Cyan

    foreach ($t in $targets) {
        $alias   = if ($t.Alias) { $t.Alias } else { $t.cluster }
        $sshFunc = "$($t.cluster)-ssh"
        Write-Host "  querying $alias ($($t.cluster)) ..." -ForegroundColor Cyan

        if (-not (Get-Command $sshFunc -ErrorAction SilentlyContinue)) {
            Add-Problem -Cluster $alias -Stage 'ssh-helper' -Detail "function '$sshFunc' not defined by Load-Config.ps1"
            continue
        }
        try {
            $raw = & $sshFunc -Command $cmd 2>&1
            $lines = @($raw | ForEach-Object { [string]$_ })
            $sources.Add([PSCustomObject]@{
                Cluster = $alias; Source = "$sshFunc"; ClusterName = $t.cluster; Lines = $lines
            })
        }
        catch {
            Add-Problem -Cluster $alias -Stage 'ssh' -Detail $_.Exception.Message
        }
    }
}

# --- Parse and normalise ----------------------------------------------------------
if ($SaveRaw -or $ReplayFrom) {
    # In replay mode the raw files already exist; only a live run needs to persist them.
}
if ($SaveRaw -and -not $ReplayFrom) {
    $null = New-Item -ItemType Directory -Path (Join-Path $OutputPath 'raw') -Force
}

foreach ($s in $sources) {
    if ($SaveRaw -and -not $ReplayFrom) {
        $s.Lines | Set-Content -LiteralPath (Join-Path $OutputPath "raw\$($s.Cluster).txt") -Encoding utf8
    }

    $parseErrors = $null
    $rows = @(ConvertFrom-OntapSnapshotCsv -Lines $s.Lines -ParseErrors ([ref]$parseErrors))

    foreach ($pe in @($parseErrors)) {
        if ($pe) { Add-Problem -Cluster $s.Cluster -Stage 'parse' -Detail "$($pe.Reason): $($pe.Line)" }
    }
    if ($rows.Count -eq 0) {
        Add-Problem -Cluster $s.Cluster -Stage 'parse' -Detail 'no snapshot rows recognised in output'
        continue
    }

    $clusterName = if ($s.PSObject.Properties.Name -contains 'ClusterName' -and $s.ClusterName) {
        $s.ClusterName
    } else { $s.Cluster }

    $recs = @($rows | ConvertTo-SnapshotRecord -Cluster $s.Cluster -ClusterName $clusterName -Now $now)
    foreach ($r in $recs) { $records.Add($r) }
    Write-Host "    $($s.Cluster): $($recs.Count) snapshots" -ForegroundColor Green
}

if ($records.Count -eq 0) {
    Write-Host "`nNo snapshots collected. See problems below." -ForegroundColor Red
    if ($problems.Count) { $problems | Format-Table -AutoSize }
    exit 1
}

# --- Rank, bucket, report ---------------------------------------------------------
$set = Get-SnapshotReportSet -Records $records.ToArray() `
    -AgeDays $AgeDays -LargeThresholdBytes $largeBytes `
    -TopOldest $TopOldest -TopLargest $TopLargest -Now $now

$reportColumns = @('Cluster', 'ClusterName', 'Svm', 'Volume', 'Snapshot',
    'CreateTime', 'CreateTimeText', 'AgeDays', 'SizeBytes', 'SizeDisplay', 'SizeText',
    'SnapmirrorLabel', 'State', 'Busy', 'Owners', 'Locked', 'LockReason')

function Export-Report {
    param([string]$Name, [object[]]$Data, [string[]]$Columns = $reportColumns)
    $path = Join-Path $OutputPath $Name
    if (-not $Data -or @($Data).Count -eq 0) {
        # Still emit the file so a consumer can tell "ran and found none" from "never ran".
        '' | Select-Object @{N = 'Note'; E = { 'no rows' } } | Export-Csv -LiteralPath $path -NoTypeInformation -Encoding utf8
    }
    else {
        $first = @($Data)[0]
        $cols  = @()
        if ($first.PSObject.Properties.Name -contains 'Rank') { $cols += 'Rank' }
        if ($first.PSObject.Properties.Name -contains 'Why')  { $cols += 'Why' }
        $cols += $Columns
        @($Data) | Select-Object $cols | Export-Csv -LiteralPath $path -NoTypeInformation -Encoding utf8
    }
    $path
}

$written = @()
$written += Export-Report -Name 'snapshots-all.csv'              -Data $set.All
$written += Export-Report -Name 'snapshots-oldest.csv'           -Data $set.Oldest
$written += Export-Report -Name 'snapshots-largest.csv'          -Data $set.Largest
$written += Export-Report -Name 'snapshots-old-candidates.csv'   -Data $set.OldCandidates
$written += Export-Report -Name 'snapshots-large-candidates.csv' -Data $set.LargeCandidates
$written += Export-Report -Name 'snapshots-unknown.csv'          -Data $set.Unknown

$summaryPath = Join-Path $OutputPath 'cluster-summary.csv'
$set.ClusterSummary | Export-Csv -LiteralPath $summaryPath -NoTypeInformation -Encoding utf8
$written += $summaryPath

if ($problems.Count) {
    $problemPath = Join-Path $OutputPath 'problems.csv'
    $problems | Export-Csv -LiteralPath $problemPath -NoTypeInformation -Encoding utf8
    $written += $problemPath
}

# Full record set as JSON, so a later run can re-threshold without re-querying.
$jsonPath = Join-Path $OutputPath 'snapshots.json'
[PSCustomObject]@{
    GeneratedAt         = $now
    AgeDaysThreshold    = $AgeDays
    LargeThresholdBytes = $largeBytes
    Stats               = $set.Stats
    Records             = $set.All
} | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding utf8
$written += $jsonPath

# --- Console summary --------------------------------------------------------------
Write-Host "`n=== Snapshot comparison ===" -ForegroundColor White
Write-Host ("  snapshots      : {0} across {1} cluster(s), {2} total" -f
    $set.Stats.Total, $set.Stats.Clusters, $set.Stats.TotalSize)
Write-Host ("  thresholds     : age >= {0} d, size >= {1}" -f $AgeDays, $set.LargeThreshold)
Write-Host ("  old candidates : {0}" -f $set.Stats.OldCandidates) -ForegroundColor Yellow
Write-Host ("  large candidates: {0}" -f $set.Stats.LargeCandidates) -ForegroundColor Yellow
Write-Host ("  locked (busy/owned): {0}" -f $set.Stats.Locked)
if ($set.Stats.SizeUnknown -or $set.Stats.DateUnknown) {
    Write-Host ("  UNMEASURED     : {0} without a size, {1} without a create-time — excluded from rankings, listed in snapshots-unknown.csv" -f
        $set.Stats.SizeUnknown, $set.Stats.DateUnknown) -ForegroundColor Yellow
}
if ($TopOldest -gt 0 -and $set.Stats.Total -gt $TopOldest) {
    Write-Host ("  NOTE: oldest report capped at -TopOldest $TopOldest of $($set.Stats.WithCreateTime) dated snapshots.") -ForegroundColor DarkYellow
}
if ($TopLargest -gt 0 -and $set.Stats.Total -gt $TopLargest) {
    Write-Host ("  NOTE: largest report capped at -TopLargest $TopLargest of $($set.Stats.WithSize) sized snapshots.") -ForegroundColor DarkYellow
}

Write-Host "`n--- Per cluster ---" -ForegroundColor Cyan
$set.ClusterSummary |
    Select-Object Cluster, Snapshots, Volumes, TotalSize, OldCandidates, LargeCandidates,
                  OldestAgeDays, LargestSize |
    Format-Table -AutoSize

Write-Host "--- Top 10 oldest ---" -ForegroundColor Cyan
$set.Oldest | Select-Object -First 10 Rank, Cluster, Svm, Volume, Snapshot, CreateTime, AgeDays, SizeDisplay |
    Format-Table -AutoSize

Write-Host "--- Top 10 largest ---" -ForegroundColor Cyan
$set.Largest | Select-Object -First 10 Rank, Cluster, Svm, Volume, Snapshot, SizeDisplay, AgeDays, CreateTime |
    Format-Table -AutoSize

if ($problems.Count) {
    Write-Host "--- Problems ($($problems.Count)) ---" -ForegroundColor Yellow
    $problems | Select-Object -First 20 | Format-Table -AutoSize
}

Write-Host "Reports written to: $OutputPath" -ForegroundColor Green
$written | ForEach-Object { Write-Host "  $(Split-Path -Leaf $_)" -ForegroundColor DarkGray }
Write-Host "`nRead-only run — no snapshot was deleted or modified." -ForegroundColor Green
